---
all:
  vars:
    ansible_user: sysadm
    ansible_ssh_pass: xsw!2345
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_pass: xsw!2345
  children:
    lxc_host:
      hosts:
        localhost:
          ansible_connection: local
          ansible_become: true
          ansible_become_method: sudo
    lxc_container:
      hosts:
        localhost:
          ansible_connection: local
          ansible_become: true
          ansible_become_method: sudo
          containers:
            - name: kafka01
              ip: 10.0.3.11
              user: sysadm
              passwd: zaq!2345
    confluent:
      hosts:
        debian9:
          apt_repositories_keys:
            - https://packages.confluent.io/deb/5.0/archive.key
          apt_repositories:
            - deb [arch=amd64] https://packages.confluent.io/deb/5.0 stable main
