---
all:
  vars:
    ansible_user: sysadm
    ansible_ssh_pass: zaq!2345
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_pass: zaq!2345
  children:
    lxc_host:
      hosts:
        localhost:
          ansible_connection: local
          ansible_become: true
          ansible_become_method: sudo
    lxc_container:
      hosts:
        localhost:
          ansible_connection: local
          ansible_become: true
          ansible_become_method: sudo
          containers:
            - name: kafka01
              ip: 10.0.3.11
              user: sysadm
              passwd: zaq!2345
            - name: kafka02
              ip: 10.0.3.12
              user: sysadm
              passwd: zaq!2345
            - name: kafka03
              ip: 10.0.3.13
              user: sysadm
              passwd: zaq!2345
    local_sshkey:
      hosts:
        kafka01:
        kafka02:
        kafka03:
    server-tools:
      hosts:
        kafka01:
        kafka02:
        kafka03:
    cross_hosts_file:
      hosts:
        kafka01:
        kafka02:
        kafka03:
    confluent:
      hosts:
        kafka01:
          ZK_serverid: 1
        kafka02:
          ZK_serverid: 2
        kafka03:
          ZK_serverid: 3
      vars:
        apt_repositories_keys:
          - https://packages.confluent.io/deb/5.0/archive.key
        apt_repositories:
          - deb [arch=amd64] https://packages.confluent.io/deb/5.0 stable main
        ZK_leaderport: 2888
        ZK_electionport: 3888
