---
  # - debug: msg='{{ groups["confluent"] | extend_join(",", "http://", ":2181")}}'
  #   tags:
  #     - mydebug

  - name: Усстановка пакетов для работы Apt
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items: "{{ apt_support_package }}"
    tags:
      - install

  - name: Добавить ключи для репозиториев
    apt_key:
      url: "{{item}}"
      state: present
      validate_certs: no
    tags:
      - install
    with_items: "{{ apt_repositories_keys }}"

  - name: Добавить репозитории
    apt_repository:
      repo: "{{ item }}"
      state: present
    with_items: "{{ apt_repositories }}"
    tags:
      - install

  - name: Обновить метаданные репозитория
    apt:
      update_cache: yes
    tags:
      - install

  - name: Установить пакеты
    apt:
      name: "{{ item }}"
      state: present
      allow_unauthenticated: yes
    with_items: "{{ packages }}"
    tags:
      - install

  - name: Настройка ZooKeeper
    block:
      - name: Заполнить список нод в кластере
        template:
          src: zookeeper.properties.j2
          dest: /etc/kafka/zookeeper.properties

      - name: Добавить MyID ZooKeeper
        lineinfile:
          path: /var/lib/zookeeper/myid
          state: present
          regexp: "^.*$"
          create: yes
          line: "{{ ZK_serverid }}"

  - name: Настройка Kafka
    block:
      - name: Установить id брокера
        lineinfile:
          path: /etc/kafka/server.properties
          create: yes
          regexp: '^#*{{ item.key }}'
          line: '{{ item.key }}={{ item.value }}'
        with_items:
          - key: broker.id
            value: '{{ brocker_id }}'
          - key: listeners
            value: "PLAINTEXT://{{ inventory_hostname }}:9092"
        notify:
          - "restart kafka"

      - name: Прописать все доступные инстансы zookeeper
        lineinfile:
          path: /etc/kafka/server.properties
          regexp: '^#*zookeeper.connect='
          line: 'zookeeper.connect={{ groups["confluent"] | extend_join(",","", ":2181")}}'
        notify:
          - "restart kafka"


  - name: Включить автозагрузку служб
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - confluent-zookeeper
      - confluent-kafka
      - confluent-schema-registry
      - confluent-kafka-rest
      # - confluent-connect
      # - confluent-ksql-server
