---
  - name: Заполнить hosts для контейнеров
    lineinfile:
      path: /etc/hosts
      regexp: '\s+{{ item.name }}\s*'
      line: "{{ item.ip }}  {{ item.name }}"
    with_items: "{{ containers }}"

  - name: Создать контейнер
    lxc_container:
      name: "{{ item.name }}"
      container_log: true
      template: debian
      state: started
      backing_store: dir
      template_options: --release stretch
      container_command: |
        apt-get update
        apt-get install -y sudo ssh
        adduser --gecos "{{ item.user }},None,None,None" --disabled-password {{ item.user }}
        echo {{ item.user }}:{{ item.passwd }} | chpasswd
        usermod -a -G sudo {{ item.user }}
        echo 'hello world.' | tee /opt/started
        if [[ -f "/opt/started" ]]; then
            echo 'hello world.' | tee /opt/found-started
        fi
      container_config:
        - "lxc.net.0.ipv4.address = {{ item.ip }}/24"
      container_log_level: DEBUG
      # container_log: yes
    register: lxc_container_info
    with_items: "{{ containers }}"
