---
  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    when:
      inventory_hostname != 'localhost'
    with_items:
      - sysadm
