---

- hosts: all
  gather_facts: False
  roles:
    - known_hosts
  tags:
    - always

- hosts: all
  gather_facts: False
  roles:
    - raw_python
  tags:
    - raw_python

- hosts: lxc_host
  roles:
    - lxc_host
  tags:
    - lxc_host

- hosts: confluent
  roles:
    - confluent
  tags:
    - confluent
