---

- hosts: all
  gather_facts: False
  roles:
    - known_hosts
  tags:
    - always

- hosts: all
  gather_facts: False
  roles:
    - raw_python
  tags:
    - raw_python

- hosts: local_sshkey
  roles:
    - local_sshkey
  tags:
    - local_sshkey

- hosts: server-tools
  roles:
    - server-tools
  tags:
    - server-tools

- hosts: cross_hosts_file
  roles:
    - cross_hosts_file
  tags:
    - cross_hosts_file

- hosts: confluent
  roles:
    - confluent
  tags:
    - confluent
