---
  - name: Установить паакеты для lxc
    apt:
      name: "{{ item }}"
      state: present
    with_items: "{{ lxc_packages }}"

  - name: Раскоментировать настройку lxc dnsmasq.conf
    lineinfile:
      path: /etc/default/lxc-net
      create: yes
      regexp: '^[#\s]*LXC_DHCP_CONFILE'
      line: 'LXC_DHCP_CONFILE=/etc/lxc/dnsmasq.conf'
    notify:
      - "restart lxc"
      - "restart lxc-net"

  - name: Создать файл /etc/lxc/dnsmasq.conf
    file:
      path: /etc/lxc/dnsmasq.conf
      state: touch
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"

  # - name: Установка lxc-python2 через pip
  #   pip:
  #     name: lxc-python2
