---
  - name:  Очистить kntnown_hosts на локальной машине (Name)
    local_action:
      module: known_hosts
      name: "{{ inventory_hostname }}"
      state: absent
      hash_host: yes
    when:
      inventory_hostname != 'localhost'
    tags:
      - always

  - name:  Очистить kntnown_hosts на локальной машине (IP)
    local_action: shell ssh-keygen -R $(getent hosts {{ inventory_hostname }} | awk '{ print $1 }')
    when:
      inventory_hostname != 'localhost'
    ignore_errors: yes 
    tags:
      - known_hosts

  - name: Заполнить known_hosts на локальной машине
    local_action:
      module: known_hosts
      name: "{{ inventory_hostname }}"
      key: "{{ lookup('pipe', 'ssh-keyscan {{ inventory_hostname }}') }}"
      state: present
    when:
      inventory_hostname != 'localhost'
    tags:
      - always
