---
  - name: Заполнить known_hosts на локальной машине
    local_action:
      module: known_hosts
      name: "{{ inventory_hostname }}"
      key: "{{ lookup('pipe', 'ssh-keyscan {{ inventory_hostname }}') }}"
      state: present
    when:
      inventory_hostname != 'localhost'
    tags:
      - always

#  - name: Bootstrap a host without python installed
#    raw: apt-get install -y python
#    ignore_errors: yes
