---
  - name:  Очистить kntnown_hosts на локальной машине
    local_action:
      module: known_hosts
      name: "{{ inventory_hostname }}"
      state: absent
      hash_host: yes
    when:
      inventory_hostname != 'localhost'
    tags:
      - always

  - name: Заполнить known_hosts на локальной машине
    local_action:
      module: known_hosts
      name: "{{ inventory_hostname }}"
      key: "{{ lookup('pipe', 'ssh-keyscan {{ inventory_hostname }}') }}"
      state: present
    when:
      inventory_hostname != 'localhost'
    tags:
      - always

  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    when:
      inventory_hostname != 'localhost'
    with_items:
      - sysadm

#  - name: Bootstrap a host without python installed
#    raw: apt-get install -y python
#    ignore_errors: yes
